name: PrisonTweaks
version: ${project.version}
main: me.shakeforprotein.prisontweaks.PrisonTweaks
authors: [ShakeforProtein]
website: http://play.treebomc.com
api-version: 1.13

commands:
  prisontweaks:
    description: ''
    usage: '<Command>'

permissions:
  prisontweaks.updatechecker:
    default: op
    description: ''
  prisontweaks.clearviptimer:
    default: op
    description: ''
  prisontweaks.reload:
    default: op
    description: ''
  prisontweaks.setthrow:
    default: op
    description: ''