name: PrisonTweaks
version: ${project.version}
main: me.shakeforprotein.prisontweaks.PrisonTweaks
authors: [ShakeforProtein]
website: http://play.treebomc.com
api-version: 1.13

commands:
  prisontweaks:
    description: ''
    usage: '<Command>'

permissions:
  prisontweaks.updatechecker:
    default: op
    description: 'Notify player on join if there is an update to the plugin'
  prisontweaks.clearviptimer:
    default: op
    description: 'Enables use of /prisontweaks clear'
  prisontweaks.reload:
    default: op
    description: 'Enables use of /prisontweaks save and reload'
  prisontweaks.setthrow:
    default: op
    description: 'Enables use of /prisontweaks setTntThrow'
  pvip.perm:
    default: false
    description: 'Enables use of /prisontweaks givenewpick'
    
